Repository tetsuya-ki/discord-bot-heroku, pull requests merged in 2021-02, with the labels that each got.

#54 大喜利機能の修正
  .gitignore
  cogs/gamecog.py
  cogs/modules/files/.env-docker.sample
  cogs/modules/files/.env.sample
  cogs/modules/ohgiri.py
  cogs/modules/savefile.py
  cogs/modules/settings.py
Labels: bug, enhancement

#55 Feature add ohgiri
  .gitignore
  cogs/gamecog.py
  cogs/modules/files/.env-docker.sample
  cogs/modules/files/.env.sample
  cogs/modules/files/ohgiri.json
  cogs/modules/ohgiri.py
  cogs/modules/savefile.py
  cogs/modules/settings.py
Labels: bug, enhancement

#56 大喜利機能の修正、/purgeの挙動を環境変数で設定できるよう修正、Dockerfileの環境変数追加
  Dockerfile
  cogs/admincog.py
  cogs/gamecog.py
  cogs/modules/files/.env-docker.sample
  cogs/modules/files/.env.sample
  cogs/modules/ohgiri.py
  cogs/modules/settings.py
  readme.md
Labels: bug, documentation

#57 discord.pyを1.6.0に変更。大喜利機能やゲーム機能全般の改善
  cogs/admincog.py
  cogs/gamecog.py
  cogs/modules/ohgiri.py
  cogs/onmessagecog.py
  cogs/reactionchannelercog.py
  readme.md
  requirements.txt
Labels: bug, documentation, enhancement

#59 リアクションチャンネラー機能の拡張し、Webhookも登録できるように変更(issue #58)
  Dockerfile
  cogs/modules/files/.env-docker.sample
  cogs/modules/files/.env.sample
  cogs/modules/reactionchannel.py
  cogs/modules/settings.py
  cogs/reactionchannelercog.py
  readme.md
Labels: enhancement

#60 Feature/#47
  cogs/admincog.py
  readme.md
Labels: enhancement

#61 Developから取り込み(リアクションチャンネラー機能拡張(Webhook)、キーワード指定削除機能追加)
  Dockerfile
  cogs/admincog.py
  cogs/modules/files/.env-docker.sample
  cogs/modules/files/.env.sample
  cogs/modules/reactionchannel.py
  cogs/modules/settings.py
  cogs/reactionchannelercog.py
  readme.md
Labels: enhancement

#63 Bugfix/#62
  cogs/modules/ohgiri.py
  cogs/modules/radiko.py
  cogs/modules/reactionchannel.py
  cogs/modules/scrapboxsidandpnames.py
  cogs/reactionchannelercog.py
Labels: bug
